site_name: napari-foobar
site_description: A simple plugin to use with napari
site_author: Napari Developer

theme: readthedocs

repo_url: https://github.com/tlambert03/napari-foobar

pages:
- Home: index.md
